# 项目相关配置
vendetech:
  # 名称
  name: tsms
  # 版本
  version: 2.0.0
  # 版权年份
  copyrightYear: 2019
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/vendetech/uploadPath，Linux配置 /home/vendetech/uploadPath）
  profile: D:/vendetech/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8086
  # sit server port
  #  port: 8686
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# 日志配置
logging:
  level:
    com.vendetech: debug
    org.springframework: warn

# Spring配置
spring:
  # 数据库
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        # prod
        url: jdbc:mysql://localhost:3306/vendetsms_prod?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: '000000'

      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  #  # 配置文件别名
  #  profiles:
  #    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 生产环境redis数据库
    database: 0
    # password: vende3328
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.vendetech.project.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen:
  # 作者
  author: vendetech
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.vendetech.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_


# 电签资源配置
base:
  url: http://y.vendetech.com/tsms/api
sign:
  nginxPath: http://y.vendetech.com/tsms/sign
  baseFilePath: /home/wd/serverdata/prod/sign
  tplPath: ${sign.baseFilePath}/template
  pdfPath: ${sign.baseFilePath}/downloadPdf
  companyImgPath: ${sign.baseFilePath}/img/company
  sendMsg: 【法大大】尊敬的用户，文德数慧给您发来一份合同，请按照以下路径进行签署：文德数慧员工服务平台-员工电签-我的协议。
payConfig:
  bankConf: ${sign.baseFilePath}/payconfig/bank.json
  tltBankConf: ${sign.baseFilePath}/payconfig/tlt_bank.json
fdd:
  appId: 500442
  appSecret: Z2mncvHBHUwEeQTqbM4wwoLa
  version: 2.0
  host:  http://textapi.fadada.com:9999/api2/
  customerId: 393E42D53304C0E17F7238D665EA9300


# portalHost
portal:
  host:
    api: http://y.vendetech.com/api

# dingTalk
dingTalk:
  corpId: dingbc17cb43c9e698b435c2f4657eb6378f
  agentId: 1083043118
  appKey: dingnmcdxwzyjz6id73m
  appSecret: iV9GwRzRqgFCEw17RRlr8zYmNPYEz78atX7sQxGmjDlF3WR__Pf_lR1FzOn8rRRP
  appId: dingoaelxu4xkg3p66jlqw
  appScanSecret: tBpRO50gexMColRzdeBQk8R9xhlHA2TFDCnIGuqJ38FlAo4HHcUyT3uFF5LwgGjK